### ISSUE TITLE
I think puppetlabs-concat might be a requirement also

### ISSUE THREAD

**Issue by piersdd** [saz/puppet-ssh#103]
Being new to Puppet.. I could not get the ssh module to deploy to a node without installing puppetlabs-concat on the master.
Both hosts are Ubuntu 14.04.2
Puppet versions are; node 3.7.4, master 3.7.5 

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type concat at /etc/puppet/modules/ssh/manifests/server/config.pp:9 on node pn-test.playground.uno
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by absz1980** [comment]
Hello, SAZ!
I have a similar problem
hosts are versions are; node RHEL 6.5, master RHEL 7.1
Puppet versions are; node 3.6.2, master 3.6.2
Stdlib is installed

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type concat at /etc/puppet/environments/KT_MGTS_Library_PuppetForge_4/modules/ssh/manifests/server/config.pp:9 on node test-asrz-bl01.mgts.corp.net
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by antaflos** [comment]
puppetlabs-concat is definitely a requirement for this module, yes. Should be added to metadata.json.

**Comment by saz** [comment]
This isn't an issue of my module, but looks like a missing requirement.
