### ISSUE TITLE
Dependency error during rake spec

### ISSUE THREAD

**Issue by phathocker** [saz/puppet-ssh#106]
I'm getting this error when I run <code>rake spec</code> from my roles/profiles.  Is there a missing fact that I need to include?  It looked like $::osfamily drove everything in the params.pp.

<pre>
    Failure/Error: it { should contain_class('roles') }
     Puppet::Error:
       Could not find resource 'File[/etc/ssh/sshd_config]' for relationship on 'Service[sshd]'
</pre>

Here is my simple spec.  I tried including lsbdistdescription, lsbdistid, interfaces, and ipaddress_eth0 because you had them in your spec.

<pre>
require 'spec_helper'

describe 'roles' do
  context 'supported operating systems' do
    ['RedHat'].each do |osfamily|
      describe "roles class without any parameters on #{osfamily}" do
        let(:hiera_config) { 'spec/fixtures/hiera/hiera.yaml' }
        let(:params) {{ }}
        let(:facts) {{
          :osfamily => osfamily,
          :operatingsystem => osfamily,
          :operatingsystemmajrelease => '6',
          :operatingsystemrelease     => '6.3',
          :lsbdistdescription => 'Red Hat Enterprise Linux Server release 6.6 (Santiago)',
          :lsbdistid => 'RedHatEnterpriseServer',
          :interfaces => 'eth0',
          :ipaddress_eth0 => '192.168.1.1',
          :concat_basedir => '/tmp'
        }}

        it { should compile.with_all_deps }
        it { should contain_class('roles') }
      end
    end
  end
end
</pre>

**Comment by saz** [comment]
I've pinned puppetlabs-concat to 1.2.0 in the spec tests, but will investigate this further.
