### ISSUE TITLE
puppetlabs-concat v1.2.1 with file_concat breaks sshd_config ~> Service

### ISSUE THREAD

**Issue by geoffgarside** [saz/puppet-ssh#109]
When using this module with the latest version of puppetlabs-concat the File/Service relationship fails.

```
File[$ssh::params::sshd_config] ~> Service[$ssh::params::service_name]
```

as the File resource doesn't exist. The new concat module doesn't create a File resource by the looks of things anymore. With some very loose testing I've found that 

1. Removing the File ~> Service relationship chains seems fine, as the Class ~> Class relationships between the 'ssh::server::config' and 'ssh::server::service' are defined.
2. Changing the File ~> Service relationship to Concat ~> Service works fine as the relationship is now with the public module name rather than the internal File resource.

I'm not completely sure which method would be the best.

**Comment by saz** [comment]
I think, the second option is the better one, but I'll need to investigate if this is backwards compatible.

**Comment by tedivm** [comment]
:+1:

**Comment by tedivm** [comment]
I went with a third option- I set the concat resource to subscribe the service resource to it. Any change to concat will trigger a refresh of the service, and this should work regardless of the version of the concat module in use.

**Comment by geoffgarside** [comment]
There is also a File ~> Service relationship defined in manifests/server.pp as well as in manifests/server/config.pp

**Comment by geoffgarside** [comment]
Using one of the 1.2.x versions of puppetlabs-concat, 1.2.0, 1.2.1 or 1.2.2 works fine. I think I might have been using master instead of a versioned tag. If you use 2.0.0 though it does break again.

**Comment by cpick** [comment]
I hit this bug as soon as I tried upgrading puppetlabs-concat to 2.0.1.
I've been working around the issue by pinning it back to 1.2.1 (the version I had used previously).

**Comment by tedivm** [comment]
You guys can use my [dev branch](https://github.com/tedivm/puppet-ssh/tree/dev)- I've merged this and another bug fix into it.
