### ISSUE TITLE
Support for merging options hash using multi-level hierarchy in hiera

### ISSUE THREAD

**Issue by buzzdeee** [saz/puppet-ssh#110]
I generally appreciate the idea behind it, but
I think the merge 3b2b2fb3097ec74d349d07cdc67a1f97820cc0b4 broke my ssh setup.

In my hierarchy, I have ssh::server_options defined, but no ssh::server::options.

in init.pp, these options are taken and passed to the server.pp. However, there, the selector, doesn't work. (It also doesn't work in init.pp, but there it's not recognized ;)

I wrote little test manifest:

class test {
 $blah = hiera_hash('something', undef)

 $blubb = $blah ? {
   undef => "yalla",
   default => "foo bar",
 }

 notify {"$blubb":}

}

Which spits out:
Notice: Compiled catalog for galen.l00-bugdead-prods.de in environment production in 1.98 seconds
Info: Applying configuration version '1431328078'
Notice: foo bar
Notice: /Stage[main]/Test/Notify[foo bar]/message: defined 'message' as 'foo bar'
Notice: Finished catalog run in 0.90 seconds

so the selectors used in the ssh module always fall back to the default.
Don't know what's wrong, if it is not possible to define 'undef' as default value?

This happens for me on OpenBSD with puppet-3.7.4p2, and ruby21-hiera-1.3.4

my current workaround is to use ssh::client::options and ssh::server::options in my Hiera hierarchy.

Don't know really how to work around it, i.e. A fallback value should be specified, as hiera_hash would bail out if it cannot find anything. Changing the default value to an empty hash {}, I haven't tried it, but I think the selectors would not like this. Don't know if it would be possible to have a string as default value, i.e. "Nothing Found", that then should work with the selector at least.

Sebastian

**Comment by saz** [comment]
This should be working in the current master and I'll release a new version, as soon as all tests are passing.
