### ISSUE TITLE
Problem with server_options argument when not using hiera

### ISSUE THREAD

**Issue by olofhellqvist** [saz/puppet-ssh#111]
Hi.
We are having problems with the 2.6.0 release:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Could not find data item ssh::server_options in any Hiera data file and no default supplied at /etc/puppetlabs/puppet/thirdparty_modules/ssh/manifests/init.pp:9:27

We are not supplying server_options through hiera, we are using the server_options argument

Best Regards Olof Hellqvist

**Comment by tedivm** [comment]
This is fixed with #117, should @saz ever merge it.

**Comment by saz** [comment]
It's fixed in master and I'll release a new version, as soon as all tests are passing.
