### ISSUE TITLE
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Failed to parse template ssh/sshd_config.erb:

### ISSUE THREAD

**Issue by tedivm** [saz/puppet-ssh#112]
I'm getting the same issue as #26, however I am using ruby 1.9.3. 

I've managed to replicate this issue and think I have *one* of the causes. In hiera if I leave the ports as integers instead of strings this error appears-

Error:
```
  server_options:
    Port:
      - 22
```

No error:
```
  server_options:
    Port:
      - '22'
```

You may want to make a note of this.

**Comment by saz** [comment]
Thanks for this. I'll have a look at it.

**Comment by TJM** [comment]
Yes, it also happens if you do not use an array.

The following works:
```yaml
ssh::server_options:
  Protocol: '2'
  Port: '22'
```

but if you don't quote the '22' it fails.. Note that in the past I have also had issues with not quoting "yes" and "no" values :)

~tommy

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Failed to parse template ssh/sshd_config.erb:
  Filepath: /etc/puppet/environments/epph/modules/ssh/templates/sshd_config.erb
  Line: 23
  Detail: undefined method `strip' for 22:Fixnum
 at /etc/puppet/environments/epph/modules/ssh/manifests/server/config.pp:13 on node 
```
