### ISSUE TITLE
Allow for Sshkey's to be only "realized" from the current environment

### ISSUE THREAD

**Issue by TJM** [saz/puppet-ssh#116]
I have a "multi-tennant" puppet server where each customer has their own puppet environment. I know that I can always set `storeconfigs_enabled => false`, but I would like the hosts to "send" their host keys, but only retrieve host keys from the same puppet environment. Does this make any sense? I honestly think it would be a fairly easy change, but if there is no desire for it, maybe I will just disable the storeconfigs option.

**Comment by saz** [comment]
Sure, just send in a pull request, and I'll be happy to merge it!

Also, if it's possible, I'd be interested in your puppet master setup.

**Comment by TJM** [comment]
I have just disabled the storeconfigs part for now. SSH is not allowed between the hosts anyhow, so its a moot point. I did a "case study" with The Foreman guys https://www.youtube.com/watch?v=MsawKGHkb9Q .. a bit offtopic ;) Thanks.
