### ISSUE TITLE
could not find resource File [/etc/ssh/sshd_config]

### ISSUE THREAD

**Issue by kevinpascoe** [saz/puppet-ssh#119]
Get this when running on a fresh install of puppet 3.8 with both server and client being red hat 6
Any ideas?

**Comment by jaredcurtis** [comment]
I believe this is the same issue as #109

**Comment by saz** [comment]
This is due to newer releases of the concat module. This is fixed in master and I'll release a new version of this module, as soon as all tests are passing.
