### ISSUE TITLE
'Could not find resource 'File[/etc/ssh/sshd_config]' for relationship on 'Service[ssh]'

### ISSUE THREAD

**Issue by mrichar1** [saz/puppet-ssh#123]
I'm getting the above error when I try to use this module - I'm trying it out in test against puppet 4.x so this might just boil down to 'don't do that', but I thought I'd submit anyway in case it's unrelated.

It seems to make no difference whether or not openssh-server is installed or /etc/ssh/sshd_config exists - if that helps?

**Comment by stjeanp** [comment]
It's fixed in the source, but we're waiting on a new module to be pushed out to the forge.

**Comment by saz** [comment]
This will be fixed in the newest release.
