### ISSUE TITLE
Module broken on 3.7.4

### ISSUE THREAD

**Issue by centromere** [saz/puppet-ssh#124]
When trying to include this module without any hiera options, I get the following error:

    Error: Evaluation Error: Error while evaluating a Function Call, create_resources(): second argument must be a hash at /etc/puppet/modules/ssh/manifests/init.pp:46:3

The reason is that in init.pp, `$fin_users_client_options` is a string, not a hash. This kind of problem was mentioned in this commit: cb626fd

**Comment by vortura** [comment]
More detail on this problem is available at https://groups.google.com/forum/#!msg/puppet-users/Q0jrR9grbFI/oAc0Y5hTGtsJ

**Comment by saz** [comment]
This should be fixed in the current master
