### ISSUE TITLE
 File[$ssh::params::sshd_config] file resource missing?

### ISSUE THREAD

**Issue by dhajoshi** [saz/puppet-ssh#125]
When you define "File[$ssh::params::sshd_config] ~> Service[$ssh::params::service_name]" .. i am getting error 

Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find resource 'File[/etc/ssh/sshd_config]' for relationship on 'Service[sshd]'

this happened after i added concat module i guess .. i think we need "Concat[$ssh::params::sshd_config]"

**Comment by saz** [comment]
What is the version of this module in your installation?

**Comment by dhajoshi** [comment]
"2.6.0"

**Comment by jd-daniels** [comment]
This happens when you use concat 2.0. Which has been deleted from forge citing:

"Due to PUP-1963, puppetlabs-concat 2.x releases are being deleted due to breakage in critical functionality."
