### ISSUE TITLE
What is <<| |>> ?

### ISSUE THREAD

**Issue by MG2R** [saz/puppet-ssh#128]
This is more of a question, rather than an issue, but what is the <<| |>> and how does it work? I found it in knownhosts.pp whilst debugging an issue I'm having with SSH keys in a new environment I created. I can't seem to find the mystical space ship thing (<<| |>>) documented anywhere. I'm stumped.

**Comment by saz** [comment]
https://docs.puppetlabs.com/puppet/latest/reference/lang_exported.html

**Comment by MG2R** [comment]
Amazing. Thanks! No search engines picked found it for me.

Now I can at least get on with troubleshooting the actual problem.
