### ISSUE TITLE
Strange error when running on PE 3.8

### ISSUE THREAD

**Issue by Jmeyering** [saz/puppet-ssh#134]
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, uncaught throw :undefined_variable in thread 0x213a2 at /etc/puppetlabs/puppet/modules/ssh/manifests/hostkeys.pp:2:18 on node
```

Any thoughts on this?

**Comment by thomasbergmann** [comment]
Same error on Puppet 4.2.

**Comment by thomasbergmann** [comment]
It´s the ipaddresses function at lib/puppet/parser/functions/ipaddresses.rb causing this error.

**Comment by joshuaspence** [comment]
I am also hitting this error, on puppet 4

**Comment by petems** [comment]
It's caused by `strict_variables=true`, I think the lookups need to be re-written to not get nil lookups...

**Comment by saz** [comment]
This should be fixed in the current master
