### ISSUE TITLE
Could not find command '/var/lib/puppet/concat/bin/concatfragments.rb'

### ISSUE THREAD

**Issue by adumont** [saz/puppet-ssh#135]
I'm getting the error Could not find command '/var/lib/puppet/concat/bin/concatfragments.rb' , when using puppet module saz-ssh v2.8.1 and running a noop.

All my modules are:
# puppet module list

/etc/puppet/modules
├── puppetlabs-concat (v1.2.3)
├── puppetlabs-ntp (v4.0.0)
├── puppetlabs-stdlib (v4.6.0)
└── saz-ssh (v2.8.1)

Some facts from my fresh installation:
# facter os puppetversion

os => {"name"=>"Ubuntu", "release"=>{"major"=>"12.04", "full"=>"12.04"}, "lsb"=>{"distrelease"=>"12.04", "distcodename"=>"precise", "majdistrelease"=>"12.04", "distdescription"=>"Ubuntu 12.04", "distid"=>"Ubuntu"}, "family"=>"Debian"}
puppetversion => 3.8.1

My site.pp:

include ::ssh::server

Error:
# puppet agent --test --noop

Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for ema
Info: Applying configuration version '1436379851'
Notice: /Stage[main]/Concat::Setup/File[/var/lib/puppet/concat]/ensure: current_value absent, should be directory (noop)
Notice: /Stage[main]/Concat::Setup/File[/var/lib/puppet/concat/bin]/ensure: current_value absent, should be directory (noop)
Notice: /Stage[main]/Concat::Setup/File[/var/lib/puppet/concat/bin/concatfragments.rb]/ensure: current_value absent, should be file (noop)
Notice: Class[Concat::Setup]: Would have triggered 'refresh' from 3 events
Notice: /Stage[main]/Ssh::Server::Config/Concat[/etc/ssh/sshd_config]/File[/var/lib/puppet/concat/_etc_ssh_sshd_config]/ensure: current_value absent, should be directory (noop)
Info: /Stage[main]/Ssh::Server::Config/Concat[/etc/ssh/sshd_config]/File[/var/lib/puppet/concat/_etc_ssh_sshd_config]: Scheduling refresh of Exec[concat_/etc/ssh/sshd_config]
Notice: /Stage[main]/Ssh::Server::Config/Concat[/etc/ssh/sshd_config]/File[/var/lib/puppet/concat/_etc_ssh_sshd_config/fragments.concat.out]/ensure: current_value absent, should be present (noop)
Notice: /Stage[main]/Ssh::Server::Config/Concat[/etc/ssh/sshd_config]/File[/var/lib/puppet/concat/_etc_ssh_sshd_config/fragments]/ensure: current_value absent, should be directory (noop)
Info: /Stage[main]/Ssh::Server::Config/Concat[/etc/ssh/sshd_config]/File[/var/lib/puppet/concat/_etc_ssh_sshd_config/fragments]: Scheduling refresh of Exec[concat_/etc/ssh/sshd_config]
Notice: /Stage[main]/Ssh::Server::Config/Concat::Fragment[global config]/File[/var/lib/puppet/concat/_etc_ssh_sshd_config/fragments/00_global config]/ensure: current_value absent, should be file (noop)
Info: /Stage[main]/Ssh::Server::Config/Concat::Fragment[global config]/File[/var/lib/puppet/concat/_etc_ssh_sshd_config/fragments/00_global config]: Scheduling refresh of Exec[concat_/etc/ssh/sshd_config]
Notice: /Stage[main]/Ssh::Server::Config/Concat[/etc/ssh/sshd_config]/File[/var/lib/puppet/concat/_etc_ssh_sshd_config/fragments.concat]/ensure: current_value absent, should be present (noop)
Error: /Stage[main]/Ssh::Server::Config/Concat[/etc/ssh/sshd_config]/Exec[concat_/etc/ssh/sshd_config]: Could not evaluate: Could not find command '/var/lib/puppet/concat/bin/concatfragments.rb'
Notice: /Stage[main]/Ssh::Server::Config/Concat[/etc/ssh/sshd_config]/Exec[concat_/etc/ssh/sshd_config]: Would have triggered 'refresh' from 3 events
Notice: /Stage[main]/Ssh::Server::Config/Concat[/etc/ssh/sshd_config]/File[/etc/ssh/sshd_config]: Dependency Exec[concat_/etc/ssh/sshd_config] has failures: true
Warning: /Stage[main]/Ssh::Server::Config/Concat[/etc/ssh/sshd_config]/File[/etc/ssh/sshd_config]: Skipping because of failed dependencies
Notice: Concat[/etc/ssh/sshd_config]: Would have triggered 'refresh' from 5 events
Info: Concat[/etc/ssh/sshd_config]: Scheduling refresh of Service[ssh]
Notice: Concat::Fragment[global config]: Would have triggered 'refresh' from 1 events
Notice: Class[Ssh::Server::Config]: Would have triggered 'refresh' from 2 events
Info: Class[Ssh::Server::Config]: Scheduling refresh of Class[Ssh::Server::Service]
Notice: Class[Ssh::Server::Service]: Would have triggered 'refresh' from 1 events
Info: Class[Ssh::Server::Service]: Scheduling refresh of Service[ssh]
Notice: /Stage[main]/Ssh::Server::Service/Service[ssh]: Dependency Exec[concat_/etc/ssh/sshd_config] has failures: true
Warning: /Stage[main]/Ssh::Server::Service/Service[ssh]: Skipping because of failed dependencies
Notice: /Stage[main]/Ssh::Server::Service/Service[ssh]: Would have triggered 'refresh' from 2 events
Notice: Class[Ssh::Server::Service]: Would have triggered 'refresh' from 1 events
Notice: /Stage[main]/Ssh::Server/Anchor[ssh::server::end]: Dependency Exec[concat_/etc/ssh/sshd_config] has failures: true
Warning: /Stage[main]/Ssh::Server/Anchor[ssh::server::end]: Skipping because of failed dependencies
Notice: Stage[main]: Would have triggered 'refresh' from 3 events
Notice: Finished catalog run in 0.34 seconds

**Comment by scitechfh** [comment]
Hello,

'/var/lib/puppet/concat/bin/concatfragments.rb' is part of concat. This file isn't created in noop mode. You have to run puppet without noop first.

**Comment by saz** [comment]
What @scitechfh is saying, closing...
