### ISSUE TITLE
"ssh_client_version_full" fact uses 'sshd -V 2>&1'

### ISSUE THREAD

**Issue by erude1** [saz/puppet-ssh#140]
The "ssh_client_version_full" and "ssh_server_version_full" facts are both determined using 'sshd -V 2>&1'. I would think that the client version should be determined using 'ssh -V 2>&1'. Not sure if there's a reason for using 'sshd -V 2>&1' for both facts, but I wanted to report this anyway.

**Comment by saz** [comment]
This is fixed in the current master.
