### ISSUE TITLE
Host ordering for ssh_config matters and the sort kinda breaks that

### ISSUE THREAD

**Issue by benpillet** [saz/puppet-ssh#141]
At https://github.com/saz/puppet-ssh/blob/master/templates/ssh_config.erb#L15 the .sort breaks one of the 'features' of ssh_config.  The options are applied on a first come, first served basis.  The scenario I'm thinking of works like this:

Host _._
  ForwardAgent no
Host *
  ForwardAgent yes

I'm trying to add these to my ssh_config and in that specific order.  But, the sort makes it so I can't keep them in that order.  I got around it by changing my config to be "# 0\nHost _._" and "# 1\nHost *", but that's kinda cheesy.  Is the .sort necessary or just to keep things pretty?

**Comment by gotyaoi** [comment]
The template allows for nesting, so if you specify client_options as
```
{'Host .' => {'ForwardAgent' => 'no'},
 'Host *' => {'ForwardAgent' => 'yes'}}
```
It should work.

**Comment by benpillet** [comment]
```
{'Host *'   => {'identityfile' => '~/.ssh/funky_id_rsa'},
 'Host *.*' => {'ForwardAgent' => 'no'},
 'Host *'   => {'ForwardAgent' => 'yes'}}
```
This won't work because 'Host *' is listed twice and the hash won't store both of them.  I could make them different with 'Host * # 1' and 'Host * # 2' but that's kinda cheesy.  And, regardless I'm not guaranteed what the ordering is unless I'm using a newer version of ruby/puppet that uses the OrderedHash underneath.

**Comment by rfletcher** [comment]
> Is the .sort necessary or just to keep things pretty?

Some kind of strict order is necessary to keep the puppet catalog consistent from run to run. Ruby < 1.9.x doesn't preserve hash key order, so the convention in Puppet-land is to ensure consistent results by sorting hash keys before dumping them somewhere.

(I'm not a contributor to puppet-ssh, I just had the same issue re: preserving host entry order and ended up here. Thanks for your workaround. Agree it's ugly, but it'll work for now now.)

**Comment by saz** [comment]
@benpillet Sorting is required, as long as there might be people relying on this module and using ruby 1.8. It should not be required anymore with ruby > 1.8.
But I don't see a good way of resolving your issue without
a) dropping support for ruby < 1.9
b) adding a check inside the template for version of ruby

As a) isn't a good option, as people might use this module with old releases and are not able to update,
option b) might be a way to achieve it, but it might duplicate parts of the template. This isn't a big issue, but might lead to changes only in one part of the template and not the other.

Maybe someone smarter than me comes up with a good solution to resolve this issue, I'll be happy to merge any PR.

But for now, I think the best way would be to go with the workaround.

And, btw, you're explaining the reason for the sort in your comment: https://github.com/saz/puppet-ssh/issues/141#issuecomment-134455324

**Comment by saz** [comment]
If somebody wants to send in a PR, feel free to do so. I'll close this issue.
