### ISSUE TITLE
Issue with hiera lookups in PE 3.8.1

### ISSUE THREAD

**Issue by phathocker** [saz/puppet-ssh#142]
Even though I have ssh::server_options set in hiera, my options are being ignored and the defaults are being deployed.  For example in the below, I have Port set to 22 which isn't a default but it isn't being applied in the server.pp server merged_options variable.  I've forked saz/ssh [here](https://github.com/phathocker/puppet-ssh/tree/feature-hiera-debug) with some debug notify commands and my outputs are below:

```
Notice: ssh::server_options are: {"Port"=>"22", "Protocol"=>"2", "ChallengeResponseAuthentication"=>"no", "X11Forwarding"=>"yes", "PrintMotd"=>"no", "AcceptEnv"=>"LANG LC_*", "Subsystem"=>"sftp /usr/libexec/openssh/sftp-server", "UsePAM"=>"yes"}

Notice: fin_server_options are: {"Port"=>"22", "Protocol"=>"2", "ChallengeResponseAuthentication"=>"no", "X11Forwarding"=>"yes", "PrintMotd"=>"no", "AcceptEnv"=>"LANG LC_*", "Subsystem"=>"sftp /usr/libexec/openssh/sftp-server", "UsePAM"=>"yes"}

Notice: ssh::server fin_options are: {}

Notice: ssh::server merged_options are: {"ChallengeResponseAuthentication"=>"no", "X11Forwarding"=>"yes", "PrintMotd"=>"no", "AcceptEnv"=>"LANG LC_*", "Subsystem"=>"sftp /usr/libexec/openssh/sftp-server", "UsePAM"=>"yes"}
```

**Comment by squesson** [comment]
Same problem here in 3.8.2, but solved.
I was trying to enable ssh::server only, because I'm using another module to manage sshkeys.
I could never get values from my hiera. After some debugging, I replaced in manifests/server.pp:
```ruby
$hiera_options = hiera_hash("${module_name}::server::options", undef)
```
with:
```ruby
$hiera_options = hiera_hash("${module_name}::server_options", undef)
```
Sorry I'm not a commiter, I would have to request a pull... next time maybe!

**Comment by saz** [comment]
This should be fixed in the current master
