### ISSUE TITLE
New module release?

### ISSUE THREAD

**Issue by gjngeldenhuis** [saz/puppet-ssh#169]
Any chance of getting a new version of the module released on forge?

**Comment by petems** [comment]
@saz Is it possible to get a new forge release? 👍

**Comment by alexjfisher** [comment]
@saz Any chance of this?  Thanks!

**Comment by rnelson0** [comment]
Looks like some recent merges, can you give an ETA on a new release? Thanks!

**Comment by saz** [comment]
I hope today, but I'm trying to merge as many pr as possible. Same for issue closing.

**Comment by saz** [comment]
And here we go! Report any errors with it. Thanks!

**Comment by rnelson0** [comment]
Thanks Steffan!
