### ISSUE TITLE
Possible to disable management/export of ED25519 keys?

### ISSUE THREAD

**Issue by kian** [saz/puppet-ssh#174]
I am running into an issue where the exported `ed25519` keys are confusing Puppet on older hosts that try to collect the resources; for example:

```
Apr  8 22:10:30 legacyhost puppet-agent[3607]: Failed to apply catalog: Parameter type failed on Sshkey[host.redacted.com_ed25519]: Invalid value "ed25519". Valid values are ssh-dss, ssh-rsa, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521.
```

In this case, `host.redacted.com` correctly generated the `ed25519` key but `legacyhost` doesn't support that format, hence the error.

As a workaround, I'd simply like to disable the generation/management/export of these newer key formats.

I see there's a conditional in the code: https://github.com/saz/puppet-ssh/blob/master/manifests/hostkeys.pp#L43

Is there some way to set this as a class parameter in Hiera?

Thanks for your time, and for this module in general -- it's been invaluable.

**Comment by saz** [comment]
As long as the system has ssh*key, it will be collected and distributed. There is no way around it, right now.

But feel free to send in a pull request, which adds an option to exclude specific keys (for example).
