### ISSUE TITLE
Can't add fragments with correct ordering outside of options hash

### ISSUE THREAD

**Issue by legooolas** [saz/puppet-ssh#177]
An example of what I'm trying to do:

    class profile::ssh {
      ... # Set up options hash with default settings, which might include some "match" settings
      class { '::ssh::server': options => $options_hash }
    }

    class profile::example_app {
      ... # Do some stuff to work out what groups we need to add, according to some external data
      ::ssh::server::allowgroups { "${local_groups}": }
    }

Basically this is because I don't want to add the logic for every other item which adds some allowed users or groups to the ssh profile.  This might also be useful for other settings, of course, but this is my specific example, and there is a separate "ssh::server::match_block" define which allows you to do just this for Match block entries.

So the problem then is that if you have a match entry in the options hash then it is pushed to the end of that block of settings (sensibly enough), but the default options block has order "00" set so that it is always first.  Then any other fragments (e.g. the added `::ssh::server::allowgroups` define in the example given) are unintentionally part of the Match block.

A workaround could be:
 * Push default options block order value to higher than 00
 * Create something like the `ssh::server::match_block` define but for `AllowGroups` (or perhaps a generic one which allows any options), with a lower default concat order than the match_block entry
 * Disallow "Match" entries in the options list if any other fragments come after it

(I was thinking that I could also have a `profile::ssh` child class which appends to the options hash, but will that sort of appending even work?)

Please do feel free to tell me I'm using this the wrong way and that there's a much easier way to fix this  :)

**Comment by legooolas** [comment]
(will try to get a clean patch made for this submitted as a pull request)

**Comment by saz** [comment]
I think this is fixed in the current master. If not, please reopen this issue.
