### ISSUE TITLE
Bug under windows

### ISSUE THREAD

**Issue by dominiquearpin** [saz/puppet-ssh#178]
Hi,
I got some problems with this module under windows.  I use the last snapshot of this module, but I change some files.

init.pp and param.pp I add this at the start of the files:
if ($::osfamily != 'windows') {
}

the fail in param.pp cause me a lot of trouble under Windows 2012.

Regards,

**Comment by saz** [comment]
If you're able to send in a pull request, this would be perfect!

**Comment by saz** [comment]
If you want to add support, please send in a pull request and I'll be happy to merge it.
