### ISSUE TITLE
options in hiera + options via class { 'ssh': }

### ISSUE THREAD

**Issue by ofalk** [saz/puppet-ssh#180]
Hi!

When having our default options in hiera (we have these in defaults.yaml), plus we want to set additional options (eg. Ciphers, MACs) depending on the OS, we need to merge these two.

I tried this now this way (in init.pp):
$fin_server_options = merge($hiera_server_options, $server_options)

which works fine. Do you think it makes sense this way?

Thanks,
 @ofalk

**Comment by saz** [comment]
Just use deep merging in hier a and you should be good to go. No need for a change on this module :-)

**Comment by ofalk** [comment]
We have deep merging enabled, however, that didn't bring the effect expected. Could you try and let me know if it works fot you?
