### ISSUE TITLE
Error when using `ipaddresses()` with a tunnel interface

### ISSUE THREAD

**Issue by rnelson0** [saz/puppet-ssh#183]
When I have a tunnel interface on a node, puppet runs fail with errors like:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, integer 3250225442 too big to convert to `int' at /etc/puppetlabs/puppet/environments/production/modules/ssh/manifests/hostkeys.pp:2:18 on node vm-with-tunnel
```

I do not understand why this failure occurs, as it looks like the result should be an array. Maybe it is being coerced to an integer, but I get different integer values on different runs, when the tunnel IPs do not change.

I think #165 would fix this issue as I do not want tunnel IPs added as host aliases anyway.

**Comment by rnelson0** [comment]
This is related to https://tickets.puppetlabs.com/browse/SERVER-1408. When there is no ipv6 address for an interface (or no v4 for that matter!) the `lookupvar()` fails in a uniquely horrifying manner that blows up the puppet run. My short term workaround is to create a v6 link local address, but I still think #165 is the way to go since I don't really want the tunnel IPs being added as host aliases.

**Comment by saz** [comment]
This should be fixed in the current master
