### ISSUE TITLE
"integer <number> too big to convert to `int' at" with lookupvar

### ISSUE THREAD

**Issue by esalberg** [saz/puppet-ssh#188]
Refrencing this ticket: https://tickets.puppetlabs.com/browse/SERVER-1408

I still saw the error occur after using the v2.9.0 tag of the module.  Restarting pe-puppetserver has resolved the issue for now, although based on reading through that ticket, it may come back (but maybe not before the root cause is patched in JRuby?).

I'm opening this issue to see if there's value in patching the ipaddresses function further.  As mentioned in the ticket:
val = scope.exists?(name) ? scope.lookupvar(name) : nil

I'm assuming that this would need to go into the function, but my ruby's not the strongest.  Also, if the preference is to leave things as is and wait for the root cause patch, we can monitor and restart pe-puppetserver if/when the errors start reoccurring.

**Comment by saz** [comment]
@esalberg @msweetser As far as I can see from the puppetlabs issue, this is a bug in jruby.
Can you please tell me your puppet version you're seeing this issue on?

**Comment by esalberg** [comment]
Agreed - I'm on 2016.2.1, and the fix isn't in OSS yet, let alone PE.

I just wanted to raise it in case there was some way to workaround the issue (catch the results that are tying into the JRuby bug) with the code I mentioned.  If not, no big deal, we'll restart pe-puppetserver / wait for the JRuby fix to be implemented.

**Comment by msweetser** [comment]
@saz I'm running on Puppet 4.6.1.  Could adding the hostkeys' export_ipaddresses param to the main params and setting it to false work as a temporary workaround till JRuby is fixed?  I can test it out on this end and submit a pull request.

**Comment by saz** [comment]
Is this error still there?

**Comment by saz** [comment]
As far as I can see, this should be resolved. I'll close this issue
