### ISSUE TITLE
integer too big to convert to `int' at manifests/hostkeys.pp

### ISSUE THREAD

**Issue by msweetser** [saz/puppet-ssh#189]
When running against v2.8.x and v2.9.0, I received the following errors suddenly on multiple nodes:

Sep  6 20:28:25 puppet puppet-agent[2162]: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, integer 2386042298 too big to convert to `int' at /etc/puppetlabs/code/environments/production/modules/ssh/manifests/hostkeys.pp:6:21 

This is related, I believe, to issues #183 and #188.

Oddly enough, the fix listed in #188 - restarting the Puppet server service - alleviated the problem.  However, we're still quite worried about it returning.  Suggestions?

It also appears that the export_ipaddresses parameter was added to hostkeys.pp, but there is no way to set it without directly invoking the class.

**Comment by saz** [comment]
Thanks for reporting. I'll close this issue in favor of #188
