### ISSUE TITLE
ssh_server_version_full fact fails when sshd is not installed

### ISSUE THREAD

**Issue by edestecd** [saz/puppet-ssh#191]
We get an error message on machines without sshd installed, during fact loading.

Use Case:  our lab of ubuntu desktops do not have sshd installed
Error: Error: Facter: error while resolving custom fact "ssh_server_version_full": undefined method `lines' for nil:NilClass
Suggested fix:  Check for sshd in the fact with which or an empty nil variable

**Comment by RuriRyan** [comment]
+1
ran into the same problem today as we are using minimal installations
