### ISSUE TITLE
problems adding ciphers via the PE Console

### ISSUE THREAD

**Issue by caryanderson** [saz/puppet-ssh#193]
when attempting add a list of ciphers via the PE Console to I get the following error:

Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, "aes128-ctr" is not an Array. It looks to be a String at /etc/puppetlabs/code/environments/production/modules/ssh/manifests/init.pp:460:5 on node xxx.xxx.xxx.xxx"  What is the correct syntax for adding a list of ciphers for this module via the PE Console?

**Comment by saz** [comment]
You'll need to pass in an array of one or more ciphers, but I don't know how to achieve that in PE console.
