### ISSUE TITLE
include ssh::server not working

### ISSUE THREAD

**Issue by ubellavance** [saz/puppet-ssh#194]
Hi,

I tried using only `include ssh::server` in my manifests (all my configs are in hiera), but it never worked.  If I use `include ssh` instead, it works.  Is that normal?  Luckily, it looks like it doesn't touch the client config (even though I think it should).  Version 2.9.1. stdlib 4.12.0, concat 2.2.0, puppet 3.6.2.

I want it to only manage the sshd server configuration.

Thanks,

**Comment by ubellavance** [comment]
Correction: it does affect the puppet::client, so it would be really great if `include ssh::server` would work.   `include ssh::client` seems to be working.

**Comment by ubellavance** [comment]
I totally understand, but there was absolutely no error message on the client. I spent about 2 full days on this trying to make it work until I tested with `include::ssh`.  Here's the relevant part of my manifest:

```
#  include ssh
  include ssh::server
#  include ssh::client
```
If I comment the ssh::server line and uncomment any of the 2 others, it works (server and client configs applied with ssh, only client configs with ssh::client.

The only puppet master log entries are these:

```
Oct 27 11:20:27 master puppet-master[4277]: Not collecting exported resources without storeconfigs
Oct 27 11:20:28 master puppet-master[4277]: Not collecting exported resources without storeconfigs
Oct 27 11:20:28 master puppet-master[4277]: Compiled catalog for host.example.com in environment production in 0.63 seconds
```
I even tried this:

```
class { 'ssh::server':
  storeconfigs_enabled => false,
}
```

and I get the same result, except that I don't get the `Not collecting exported resources without storeconfigs` log entry.

```
If I set the options in the class, it works:

class { 'ssh::server':
  options => {
    'PasswordAuthentication' => 'no',
    'PermitRootLogin'        => 'no',
    'Port'                   => [22, 2222],
  },
}
```
I get a bunch of log entries about not collecting but at least the config is applied on the client.  If I set the st`oreconfigs_enabled => false` in the manifest, I get the same result (it works) but no log entries.

It looks like `ssh::server` ignores hiera configs while `ssh`and `ssh::client` doesn't.

Please let me know if you need any additionnal information.

**Comment by ubellavance** [comment]
@saz Is there any other information I can give you to help you figure out what's going on?  I commented out the client part directly in the module in the meantime to be able to use it so there is no rush but I hope this can be fixed.

**Comment by saz** [comment]
Can you provide more information on your setup? I'll try to reproduce this issue then.

**Comment by ubellavance** [comment]
My puppet master is 3.6.2 on RHEL7 (EPEL repo). Clients are 3.8.7 from puppetlabs repo, one is RHEL6, the other is CentOS7. Other

**Comment by ubellavance** [comment]
I also tried using the puppet package from EPEL on the CentOS 7 server (so that the versions match), same result.   

To summarize:

- if I set the parameters in the class, `include ssh::server` works OK. I get the parameters I set in the class.
- if I set the parameters in hiera and use `include ssh::server` in my manifest, my hiera configs are ignored, I get the module's default values in sshd.conf.
- if I comment out the `ssh::client` class declaration in init.pp and use `include ssh` in my manifest, the hiera configs are applied.

I don't know how to troubleshoot any further though. I ran puppet in debug mode but it doesn't tell what values it gets from hiera.

**Comment by ubellavance** [comment]
I just tested it with the most recent master and the problem still exists, unfortunately.

**Comment by saz** [comment]
Can you give me a complete example of your hiera config for this module?

**Comment by ubellavance** [comment]
Here it is:

hostname.yaml:

```puppet
---
ssh::storeconfigs_enabled: false

# Matches RHEL7's defaults, except PasswordAuthentication and PermitRootLogin

ssh::server_options:
    AcceptEnv: 'LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION LC_ALL LANGUAGE XMODIFIERS'
    AllowTcpForwarding: 'yes'
    GSSAPIAuthentication : 'yes'
    HostKey:
      - '/etc/ssh/ssh_host_rsa_key'
      - '/etc/ssh/ssh_host_dsa_key'
    PasswordAuthentication: 'no'
    PermitRootLogin: 'no'
    PrintMotd: 'yes'
    PrintLastLog: 'yes'
    Protocol: '2'
    Subsystem: 'sftp /usr/libexec/openssh/sftp-server'
    SyslogFacility: 'AUTHPRIV'
    UsePrivilegeSeparation: 'yes'
    X11Forwarding: 'no'
```

common.yaml:

```puppet
ssh::storeconfigs_enabled: false
ssh::validate_sshd_file: true
```

**Comment by saz** [comment]
Ok. Found it :-)
if you're relying on ```include ssh::server``` your hiera config is wrong.
It should be ```ssh::server::options``` and not ```ssh::server_options```

HTH

**Comment by ubellavance** [comment]
I'll try that right away.

**Comment by saz** [comment]
To be more clear, if you're doing a ```include ssh``` you need to pass values to ```class ssh```.
If you're including any "sub"class (e.g. ssh::server) you need to pass values to ```class ssh::server```

**Comment by ubellavance** [comment]
Understood.  If I ever need to have my ssh client configs managed by puppet as well and decide to use include ssh I'll have to move my params to ssh::server_options.

**Comment by ubellavance** [comment]
Works perfectly now.  I uncommented the ssh::client code in the module, changed my params to ssh::server::options and ran puppet: no change :).  I also tried with ssh::server_options and it wanted to put the defaults in sshd.conf.  I've put comments in my hiera files regarding an eventual move to `include ssh`. Thanks a lot for your help. I'll close this issue.

**Comment by saz** [comment]
Great. Have fun with it :-)
