### ISSUE TITLE
Recurrence of `Error while evaluating a Function Call, uncaught throw :undefined_variable`

### ISSUE THREAD

**Issue by rnelson0** [saz/puppet-ssh#195]
I'm seeing this when testing on travis, which I assume doesn't have IPv6 configured as expected, given the full error message:
```
Failures:

  1) profile::base with defaults for all parameters should contain Class[profile::base]

     Failure/Error: ipaddr6 = lookupvar("ipaddress6_#{iface}")

     

     Puppet::PreformattedError:

       Evaluation Error: Error while evaluating a Function Call, uncaught throw :undefined_variable at /home/travis/build/rnelson0/controlrepo/spec/fixtures/modules/ssh/manifests/hostkeys.pp:6:21 on node testing-worker-linux-docker-c419245d-3438-linux-12.prod.travis-ci.com
```
Given the timeframe mentioned in #134 and #166, I would expect release 2.9.0 and 2.9.1 to have this fix, but it looks like [the referenced commit](https://github.com/robertvargason/puppet-ssh/blob/9e2f04a139d7598be04b1f5eb95110e3a33bf7fb/lib/puppet/parser/functions/ipaddresses.rb) did not make it into [master](https://github.com/robertvargason/puppet-ssh/blob/master/lib/puppet/parser/functions/ipaddresses.rb). I don't see any PR that references this commit, or something similar around the Aug 26th, 2016 timeframe. Was the fix merged?

If not, is there a workaround that can be used? As identified in #134, I have strict variables enabled. My testing currently uses the puppet v4.3.2 gem.

**Comment by saz** [comment]
Tests are running fine on travis with the current master. It looks like, as if this error is fixed. Please let me know, if you still see errors.
