### ISSUE TITLE
Errors under Debian7

### ISSUE THREAD

**Issue by s-hell** [saz/puppet-ssh#200]
I'm using this module to configure debian wheezy and jessie. 
The wheezy puppet client throws the following errors:

> err: /Stage[main]/Ssh::Server::Config/Concat[/etc/ssh/sshd_config]/Concat_file[/etc/ssh/sshd_config]: Failed to generate additional resources using 'generate': Invalid parameter show_diff

and 

> err: /Stage[main]/Ssh::Server::Config/Concat[/etc/ssh/sshd_config]/Concat_file[/etc/ssh/sshd_config]: Failed to generate additional resources using 'eval_generate: undefined method `[]=' for nil:NilClass

It doesn't matter whicht setting i want to configure.
Under Jessie i don't get any error. Any ideas?

**Comment by saz** [comment]
Please tell me the version number of puppet and puppetlabs-concat module you're relying on.

**Comment by s-hell** [comment]
puppet in version 3.7.2
puppetlabs-concat version 2.2.0

**Comment by saz** [comment]
This should be fixed in the current master
