### ISSUE TITLE
AuthorizedKeysCommand(RunAs|User) varies by OS

### ISSUE THREAD

**Issue by xavierholt** [saz/puppet-ssh#201]
Feature request for you!

I've got an SSHD setup I'd like to apply to both CentOS 6 and CentOS 7, but the versions shipped with each take slightly different config variables.  On CentOS 6 the required config is:

```AuthorizedKeysCommandRunAs someuser```

But on CentOS 7 it's been changed to:

```AuthorizedKeysCommandUser someuser```

Not sure what the config looks like on other OSes, but it would be great if there was a single option that could be passed in, with the module choosing the appropriate config variable.

**Comment by saz** [comment]
This can easily be done with hiera, as I'm trying to avoid to have specific parameters
