### ISSUE TITLE
Syntax error when on centos 6

### ISSUE THREAD

**Issue by inbaz** [saz/puppet-ssh#202]
Hi I do get a syntax error when on centos 6 with the ipaddresses function. When changing the second line to this it's working:
```
module Puppet::Parser::Functions
  newfunction(:ipaddresses, :type => :rvalue, :doc => <<-EOS
Returns all ip addresses of network interfaces (except lo) found by facter.
EOS
```

Is this a ruby version issue?

Cheers
Andi

**Comment by alexskr** [comment]
seems to be the ruby version issue. which makes me question whether this module should have centos 6 compatibility listed in the first place

**Comment by saz** [comment]
Can you try it with the current master?

**Comment by alexskr** [comment]
That didn't seem to resolve the problem with centos6 

The root of the issue here I think is that centos 6 comes with ruby 1.8.7 which does not support "type: rvalue" shorthand expression; it likes the good old  ":type => :rvalue".    This module breaks puppetmaster on centos6.

**Comment by saz** [comment]
Please give the current master version a try, if it's working for you.

FYI: I'll release one last version of this module with Puppet 3 support. After that, this module might rely on Puppet 4 only features (Puppet 3 is EOL since this year).

**Comment by saz** [comment]
@alexskr Any news?

**Comment by alexskr** [comment]
it is working on centos6/RHEL6 now.  Thanks!

**Comment by TexGG** [comment]
Using the current master version corrected the error for my Puppet running on Centos 6.9.
