### ISSUE TITLE
Warning: The function 'hiera_hash' is deprecated in favor of using 'lookup'

### ISSUE THREAD

**Issue by Falkor** [saz/puppet-ssh#213]
The above warning is raised under puppet 4... 

Nothing really serious but probably a special conditional treatment should be placed upon parameter collection to use the [lookup](https://docs.puppet.com/puppet/4.10/hiera_migrate_functions.html) function -- may be using the `$clientversion`variable ?

**Comment by saz** [comment]
This will be fixed in within the next two releases
