### ISSUE TITLE
Update dependency on puppetlabs/concat version 4.0.0

### ISSUE THREAD

**Issue by Falkor** [saz/puppet-ssh#214]
`puppetlabs-concat` has been recently released under 4.0.0 -- see [Update to 4.0.0 in metadata #452](https://github.com/puppetlabs/puppetlabs-concat/pull/452/commits/e682cbf9903408aa99d8f7b1a12a57674be362df) 

Thus if dependency to `puppetlabs-concat` is set to `:latest`, this raises  dependency conflicts, in particular with `saz/ssh`:

```
Conflict between puppetlabs-concat (< 3.0.0, >= 1.2.5) <https://forgeapi.puppetlabs.com> and puppetlabs-concat/4.0.0 <https://forgeapi.puppetlabs.com>
```

Not sure if it can be sufficient to simply update `metadata.json` with the appropriate version range.

**Comment by saz** [comment]
This should be fixed in the current master

**Comment by noqqe** [comment]
@saz I would like to reopen this. 

Current master `metadata.json` still says `< 3.0.0, >= 1.2.5` which makes the ssh module here not installable.
