### ISSUE TITLE
Order is important for client Host specific options

### ISSUE THREAD

**Issue by qs5779** [saz/puppet-ssh#217]
Host * is first it matches so none of the other Host options will be interrogated. I found no way to control the Host <glob> order, and Host * always sorted first.

**Comment by egon010** [comment]
Similar problem with Match options for server side.

**Comment by saz** [comment]
This might be fixed with the merge of #182

**Comment by olifre** [comment]
@saz I see #182 is still not merged yet, but I can confirm applying that patch locally solves the issue also for me. 
Is it still in the queue for getting merged? It seem it was blocked by #202 which has been solved long ago.

**Comment by saz** [comment]
This issue is fixed in the current master.
