### ISSUE TITLE
Please add a CHANGELOG

### ISSUE THREAD

**Issue by rendhalver** [saz/puppet-ssh#222]

**Comment by pioto** [comment]
Especially when you're making major version changes, it's very very helpful for your end users to have a clear listing of what backwards-incompatible (if any) changes are being made.

**Comment by pioto** [comment]
Any chance you could provide a more succinct form of https://github.com/saz/puppet-ssh/compare/v3.0.1...v4.0.0 ? Would be good to know if there are any breaking changes from this new release...

**Comment by saz** [comment]
I'll see what I can do, but fyi, I'm sticking to https://semver.org/ which means, with a major version change, one should expect breaking changes.

**Comment by pioto** [comment]
Understood, hence us wanting to know what the breaking changes were for v4.0.0. 😉

**Comment by TJM** [comment]
In other words, if I update from 3.0.1 to 4.0.0, what do I need to be aware of? what do I need to change?

**Comment by c33s** [comment]
have to upgrade from 2.9.1 to 5.0.0, a changelog would really help

**Comment by joaquin386** [comment]
From 3.1.0 to 5.0.0, so wonder what has change ....

**Comment by TJM** [comment]
eh, we moved to 5.0.0, nothing broken so far :) (that I am aware of)

**Comment by joaquin386** [comment]
thx @TJM suppose that I would do a YOLO upgrade

**Comment by c33s** [comment]
@joaquin386 as far as i can remember and what i found in my git history: in hiera i had to change `ssh::server::options:` -> `ssh::server_options:` (same for client)

**Comment by joaquin386** [comment]
@c33s thats a good one. Will take that into consideration, I will review my manifest when I do my upgrade

**Comment by TJM** [comment]
Er, I answered in haste, I was looking at saz-sudo, saz-ssh is currently 3.0.1 for me.
