### ISSUE TITLE
Purging old server keys from knownhosts not working.

### ISSUE THREAD

**Issue by TiagoTT** [saz/puppet-ssh#223]
For server keys that should get purged from `/etc/ssh/ssh_known_hosts`, puppet throws warnings like these:
```
Warning: /Stage[main]/Ssh::Knownhosts/Sshkey[old_server_ed25519]: Anchor[ssh::server::end],Anchor[ssh::client::end] still depend on me -- not purging
Warning: /Stage[main]/Ssh::Knownhosts/Sshkey[old_server_rsa]: Anchor[ssh::server::end],Anchor[ssh::client::end] still depend on me -- not purging
Warning: /Stage[main]/Ssh::Knownhosts/Sshkey[old_server_ecdsa]: Anchor[ssh::server::end],Anchor[ssh::client::end] still depend on me -- not purging
Warning: /Stage[main]/Ssh::Knownhosts/Sshkey[old_server_dsa]: Anchor[ssh::server::end],Anchor[ssh::client::end] still depend on me -- not purging
```
And the `old_server_*` keys are not removed from `/etc/ssh/ssh_known_hosts`.
If I remove the file `/etc/ssh/ssh_known_hosts` and run puppet, the file is recreated correctly and it does not contain the `old_server_*` keys.

**Comment by saz** [comment]
I'm not able to reproduce this with the current master. Please reopen, if the problem still exists.
