### ISSUE TITLE
ssh::hostkey should used trusted.certname instead of fqdn

### ISSUE THREAD

**Issue by jschaeff** [saz/puppet-ssh#226]
It seems more logical, although the usecases where it can lead to problems is a probably rare.

**Comment by saz** [comment]
I'm still not sure, if this is good or bad. Must certname be a fqdn? As far as I can see (https://puppet.com/docs/puppet/5.5/configuration.html#certname) this can be "some" value and not a fqdn only.

**Comment by saz** [comment]
Can be used instead of fqdn. See https://puppet.com/docs/puppet/latest/lang_facts_and_builtin_vars.html#trusted-facts for more details
