### ISSUE TITLE
Bad SSH server and client facts version on RHEL/CentOS

### ISSUE THREAD

**Issue by pyfontan** [saz/puppet-ssh#227]
On RH or CentOS 6 or 7, depending on the version of SSH,
sshd -V reply is : 
OpenSSH_6.6.1p1, OpenSSL 1.0.1e-fips 11 Feb 2013
OpenSSH_7.4p1, OpenSSL 1.0.1e-fips 11 Feb 2013

ssh_server_version_full or ssh_client_version_full (based on this reply) will give : 
# facter -p ssh_server_version_full
6.6.1p1,
7.4p1,
 => ending with a comma.

And no answer for ssh_client/server_version_major/revision because "full" version is wrong.

I think you should change your regexp stopping at the first space by another one, stopping at first space or comma.

Thank you.
Pierre-yves

**Comment by saz** [comment]
This is fixed in the current master.
