### ISSUE TITLE
ssh server options with if/else, without hiera

### ISSUE THREAD

**Issue by linuxmail** [saz/puppet-ssh#228]
Hello,

I try to switch from a self written SSH module to saz/puppet-ssh but have some problems to use a if/else check to overwrite some settings from ssh::server::options, for example:
```
    class {'::ssh::server':
      options => {   
         'AddressFamily'                   => 'inet',
         'TCPKeepAlive'                    => 'no',
         'ClientAliveCountMax'             => '0',
         [...]
        },
}s
  if ($yubiauth_host) {
    class { '::ssh::server':
      options => {
        'ChallengeResponseAuthentication' => 'yes',
        'AuthenticationMethods'           => 'publickey,keyboard-interactive',
      }
    }
  }
```
What ever I try, I get syntax error or class ssh::server already declared errors. I know that I can use hiera to overwrite, but at the moment I avoid Hiera :-)

Can someone help to get the correct syntax ?

O.K, after a while, I've found a way:

```
class { 'ssh':
server_options => {
....
  },
}
      if ($yubiauth_host) {
        ssh::server::config::setting { 'ChallenceResponse': key => 'ChallengeResponseAuthentication', value => 'yes' }
        ssh::server::config::setting { 'KeyboardInteractive': key => 'AuthenticationMethods', value => 'publickey,keyboard-interactive' }
      } else {
        ssh::server::config::setting { 'ChallenceResponse': key => 'ChallengeResponseAuthentication', value => 'no' }
      }
```
but I think, there is a better way, to do it.

**Comment by ubellavance** [comment]
The better way is Hiera ;).  By the way, you have a typo in ChallenceResponse should be ChallengeResponse.  It it's the only if that you create, it's not that bad.

**Comment by linuxmail** [comment]
hi @ubellavance

correct, Hiera is the way, but not at the moment :-) 
For using Hiera, there is a lot to do and we want avoid it for now.

Thanks for the typo thing :-)

**Comment by saz** [comment]
I think you should declare the class one way or the other if $yubi_host is true.
If you're declaring the class first and then again if $yubi_host is true, this will result in this error.

But nothing I can fix in my module :)
