### ISSUE TITLE
dependencie issue

### ISSUE THREAD

**Issue by schlitzered** [saz/puppet-ssh#235]
puppet complains about unresolved dependencies because of the requrement on the concat module.

in metadata.json, the requried version is specified as

```
"version_requirement":">= 1.2.5 < 3.0.0"
```

i am running the module currently with 4.0.1 without problems.

could you please fix this & issue a new release?

Kind Regards,

**Comment by marknl** [comment]
Please update this package on puppetforge so we get rid of the dependency issue.

**Comment by saz** [comment]
Fixed in the current master and a new release will be there in the next days.
