### ISSUE TITLE
SSH Config Option Issue with Ubuntu Artful

### ISSUE THREAD

**Issue by syntacticvexation** [saz/puppet-ssh#238]
Hi,

I'm not able to complete my Puppet catalog runs when using this module under Artful Ardvark. I receive the following:
==> default: /etc/ssh/ssh_config line 22: Unsupported option "rsaauthentication"
==> default: /etc/ssh/ssh_config line 23: Unsupported option "rhostsrsaauthentication"

My understanding is that these options are no longer supported by newer versions of OpenSSH:
https://forum.gitlab.com/t/ssh-unsupported-option-rsaauthentication/11198

Thanks.

**Comment by ubellavance** [comment]
Can you share your related manifests please?

**Comment by syntacticvexation** [comment]
There's a lot of modules involved in my Ubuntu build but this is a simplified version of the profile I have:
`class profile::server::ssh($ssh_port='22', $x11forwarding='no') {
	$server_options = {
		'PrintLastLog'	=> 'yes',
		'PrintMotd'		=> 'yes',
		'Port'			=> [$ssh_port],
		'X11Forwarding' => $x11forwarding,
	}
	class { 'ssh':
		server_options => $server_options
	}
}`

Those messages are then reported when doing a git clone via SSH.

**Comment by ubellavance** [comment]
I wonder where the `rsaauthentication `and `rhostsrsaauthentication `come from then? I don't see them anyhere in the module's manifests or templates. I can only see them in files/sshd_config, but I can't find where this file would be called in the manifests.  The manifests seem to be using ``/templates/sshd_config.erb`` only.

What version of the module are using? I'm assuming the master branch of this Git repo, but I just want to be sure...

**Comment by syntacticvexation** [comment]
Found it, it's in the ssh_hardening module, apologies for the confusion, I'll close this ticket.
