### ISSUE TITLE
Feature request: Ability to create multiple SSH server instances with each their own config

### ISSUE THREAD

**Issue by NeatNerdPrime** [saz/puppet-ssh#239]
Greetings @saz and issue-readers,

I am seeking a possibility to run multiple SSHD server instances on the same host. Since i already manage my current SSHD with this module i was hoping to do it this way. Unfortunately this is AFAIK not possible yet with this module.

A particular use case is for e.g.: Segragate public and management SSHD, each listening on their own interface. Example: Having your git(lab) server listen publicly on port 22 on IP-A only for the user  "git",  and having your management SSH on port 2222 on IP-B.

To bypass this I "could"  simply create another systemD unit file and sshd_config file to be used, but I don't believe that is the most elegant solution. I believe it can be possible if "converting" the ::ssh::server class into a defined resources, allowing to create multiple instances of the server. That would ease the management of those instances since you don't need to consider other types of resources to achieve this (like e.g.: ::systemd::service resources and file resources to achieve the goal).

My questions are: 
-  Would such a feature be useful to the broader public?  
- Is my approach of converting classes to defined resources the correct one? 

If there is such an interest i could create a new branch for this goal, but I'm unsure wether my approach would be the good one.

**Comment by kasimon** [comment]
This would definitely be useful.

**Comment by dderemiah** [comment]
+1 on this request.

**Comment by derfcat** [comment]
+1.

**Comment by kasimon** [comment]
Another simpler approach would be to use the `Match`feature of openssh that allows to restrict certain configuration settings to a specific port like in 

<pre>
Port 1022
Match LocalPort 1022
AllowUsers theonly1
</pre>

Here ssh listens on an additional port and allows only one user to login on this port. This should be relatively straight-forward to implement with the concat module.

**Comment by Joachim-42he** [comment]
+1 on request. 
There are scenarios, where the solution of match rules that kasimon mentioned is not sufficient: When you want to make certain that even silly changes to sshd_config will not be able to lock you out from a system that you do not have easy physical access to.

**Comment by edomaur** [comment]
+1 here too, I've even an idea on how to proceed...

**Comment by saz** [comment]
I'm happy about any pull request or input to resolve this issue

**Comment by JOJ0** [comment]
+1
I am pretty new to puppet module coding. Anyone here has a draft of this already?

**Comment by saz** [comment]
This is now merged, thanks to @SimonHoenscheid
