### ISSUE TITLE
Error 400 on SERVER: Evaluation Error:

### ISSUE THREAD

**Issue by rafaelvecchio** [saz/puppet-ssh#241]
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Failed to parse template ssh/sshd_config.erb:
  Filepath: /etc/puppetlabs/code/environments/production/modules/ssh/templates/sshd_config.erb
  Line: 29
  Detail: undefined method `strip' for :undef:Symbol
 at /etc/puppetlabs/code/environments/production/modules/ssh/manifests/server/config.pp:27:18 on node cealsoap5.brasil.latam.cea
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Please help me !!!

**Comment by saz** [comment]
Please show me the part of your manifest/hiera for this module.

**Comment by rafaelvecchio** [comment]
Sorry about,

My hiera

profile::ssh::storeconfigs_enabled: false
profile::ssh::server_options:
    Protocol: '2'
    ListenAddress:
    PasswordAuthentication: 'yes'
    PermitRootLogin: 'no'
    Port: '22'
    AllowGroups: 'sshd'
    UsePrivilegeSeparation: 'yes'
    PermitEmptyPasswords: 'no'
    IgnoreRhosts: 'yes'
    RhostsRSAAuthentication: 'no'
    MaxAuthTries: '3'
    MaxStartups: '5'
    SyslogFacility: 'AUTHPRIV'
    LogLevel: 'INFO'
    TCPKeepAlive: 'yes'
    ClientAliveInterval: '900'
    ClientAliveCountMax: '0'
    AuthorizedKeysFile: '.ssh/authorized_keys'
    UsePAM: 'yes'
    X11Forwarding: 'yes'
    AcceptEnv: 'LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION LC_AL'

**Comment by saz** [comment]
Your value for `ListenAddress` should not be empty. That's where it's failing.
