### ISSUE TITLE
Puppet5 / current stdlib support

### ISSUE THREAD

**Issue by jantman** [saz/puppet-ssh#243]
This module appears to be failing under Puppet5 and the current version of stdlib because it uses the deprecated ``validate_*()`` functions.

I'd be happy to attempt to make the fixes, but they will break  Puppet3 compatibility, so I wanted to check first.

Also, FWIW, I've started using [modulesync](https://github.com/voxpupuli/modulesync) and a modified version of [puppetlabs/modulesync-configs](https://github.com/puppetlabs/modulesync_configs) for my modules, and it seems to be a really nice way of managing all the boilerplate for modern modules.

**Comment by baurmatt** [comment]
Yes, please! :) Puppet 3 is EOL for over a year now, its definitively time to drop support. I think https://voxpupuli.org/blog/2017/01/11/migrating-to-puppet4/ describes a good way to handle this.

**Comment by pmuller** [comment]
PR #245 fixes it

**Comment by saz** [comment]
This is now fixed in the current master.

@jantman Planning on relying on modulesync for a longer time, but never got to it. Any help would be greatly appreciated
