### ISSUE TITLE
RHEL7-family and FIPS 140-2

### ISSUE THREAD

**Issue by dafydd2277** [saz/puppet-ssh#247]
DSA algorithms have been deprecated in RHEL 7-family operating systems configured for FIPS 140-2 via the `dracut-fips` package.

```
[root@[HOST] ~]# ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
DSA keys are not allowed in FIPS mode

[root@[HOST] ~]# ls -1 /etc/ssh/ssh_*
/etc/ssh/ssh_config
/etc/ssh/ssh_host_ecdsa_key
/etc/ssh/ssh_host_ecdsa_key.pub
/etc/ssh/ssh_host_ed25519_key
/etc/ssh/ssh_host_ed25519_key.pub
/etc/ssh/ssh_host_rsa_key
/etc/ssh/ssh_host_rsa_key.pub
/etc/ssh/ssh_known_hosts

```

If this module runs on a RHEL 7 FIPS host, the module will fail and `sshd` will be halted, which blocks remote access to the host and requires a console login to fix.

My suggestion is to reduce notification of missing DSA keys to `NOTICE` only for RHEL 7 hosts, and don't fail if the keys are not found.

**Comment by saz** [comment]
Any chance that you can create a pull request for that?

**Comment by saz** [comment]
Please show the exact error you're seeing

**Comment by saz** [comment]
Any updates?

**Comment by saz** [comment]
I'm closing this issue now. Feel free to open it again, if required
