### ISSUE TITLE
Deprecated hiera_hash function

### ISSUE THREAD

**Issue by krostar** [saz/puppet-ssh#248]
Hello,

On puppet forge the module is tagged at the 3.57.0 version, which generates a lot of warning due to the use of legacy/deprecated functions (a lot from the concat lib).

I saw you modified your dependencies to accept the latest updates of the concat library. In order to get rid of a maximum of deprecated warning I use this module on the latest commit of master instead of the latest release. Every concat-lib-related warning disappeared, only the following ones stayed (I'm only using the ::ssh::server class, maybe there is some in the other classes):

```sh
Warning: This method is deprecated, please use the stdlib validate_legacy function,
                    with Stdlib::Compat::Hash. There is further documentation for validate_legacy function in the README. at ["/etc/puppetlabs/code/environments/vagrant/modules/ssh/manifests/server.pp", 12]:["/etc/puppetlabs/code/environments/vagrant/site/roles/manifests/default.pp", 3]
   (location: /etc/puppetlabs/code/environments/vagrant/modules/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
Warning: The function 'hiera_hash' is deprecated in favor of using 'lookup'. See https://docs.puppet.com/puppet/5.5/reference/deprecated_language.html\n   (file & line not available)
```

Is it possible to change the `hiera_hash` call to `lookup` and the `validate_hash` to `validate_legacy` with `Stdlib::Compat::Hash` ?

Thanks for you module, it's really useful,
krostar.

**Comment by krostar** [comment]
Hi, didn't see it before but the [PR 245](https://github.com/saz/puppet-ssh/pull/245/) solve exactly this issue, is it planned to merge it soon ?

**Comment by saz** [comment]
This is fixed in the current master

**Comment by krostar** [comment]
Is it possible to tag a new release ?

**Comment by saz** [comment]
Yeah, just waiting for a little bit if there is feedback coming in before releasing a new version


Gesendet von VMware Boxer
