### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by tedivm** [saz/puppet-ssh#250]
The current version of this module on the forge is depends on an older version of the concat module (`>= 1.2.5 < 3.0.0`) which is conflicting with a lot of other modules (many are requiring `>3`). It seems that this is already updated in the master branch.

**Comment by bastelfreak** [comment]
Hey @saz. It's currently not possible to use this module without warnings. Most of the beaker tests out there rely on proper version dependency resolution from forge releases and for those it's impossible to use the module. Can you please do a new release or migrate the module to Vox Pupuli?

**Comment by saz** [comment]
As you might have seen, I've merged a couple of things. Are you currently relying on the master version of this module?

**Comment by tedivm** [comment]
Yeah, I'm using the master branch without any issues at all. The current version on the forge basically won't install on modern puppet environments due to other modules requiring a higher version of the "concat" module.

**Comment by saz** [comment]
Glad to hear. I'll do a release tomorrow.

**Comment by tedivm** [comment]
Awesome, thanks!
