### ISSUE TITLE
Evaluation Error: Error while evaluating a Resource Statement

### ISSUE THREAD

**Issue by amukiza** [saz/puppet-ssh#251]
I just noticed that when I use the new version 4.0.0, I get this error. Previous version 3.0.1 seems to work fine.

default: Error: Evaluation Error: Error while evaluating a Resource Statement, Concat[/etc/ssh/sshd_config]: parameter 'path' expects a Resource value, got String  at /etc/puppetlabs/code/environments/production/modules/ssh/manifests/server/config.pp:16 on  <host-name>

**Comment by amukiza** [comment]
Both master and agent are 4.3.2

```[vagrant@kafka ~]$ puppet master --version                                                                                                                                                                                                   
4.3.2
[vagrant@kafka ~]$ puppet agent --version                                                                                                                                                                                                    
4.3.2
```

**Comment by saz** [comment]
What's the version of the stdlib module?

**Comment by saz** [comment]
No response, closing this.
