### ISSUE TITLE
Request: add the option to include 'Match All' at the end of all match blocks

### ISSUE THREAD

**Issue by adrift42** [saz/puppet-ssh#253]
Currently we are using this module to manage our ssh servers, however we have some specific cases where the sshd_config is modified by a separate module (in this case one designed for hardening). Any options that are not included in the saz/ssh module are then appended to the end of the file.

This is fine except in the situation where match blocks are used for our sftp server. Anything appended to the file is then counted as part of the last created match block and this causes errors.

One way to work around it would be to include 'Match All' at the end of the last match block so that anything following can then be parsed correctly.

The top two answers in this following link may help explain better: https://unix.stackexchange.com/questions/67334/openssh-how-to-end-a-match-block 

I attempted to create a match block with an empty type and the name for 'all', but the concat adds all entries in alphabetically and so 'Match All' will come before any other match blocks.

**Comment by adrift42** [comment]
Actually, as I should have foreseen, there are changes each puppet run due to saz/ssh module defaults being overridden by linux_hardening module and as such can not have the one file touched by two separate modules.

I did manage to find a work around to the match all issue by including an order value:

  ssh::server::match_block { 'all':
    type    => '',
    options => { },
    order   => '51',   # default order value is 50, so this occurs afterwards
  }

**Comment by saz** [comment]
Is there still something required on this module?

**Comment by saz** [comment]
As there is no feedback, I'll close the issue. Feel free to raise it again.
