### ISSUE TITLE
Invalid value "ed25519" 

### ISSUE THREAD

**Issue by bjarnek** [saz/puppet-ssh#262]
I get the following error using version 2.8.1 of the module. I cannot however use a newer one atm as it's an older puppet sever. I tried to use a never and got a whole heap of errros :( 

```
Error: Failed to apply catalog: Parameter type failed on Sshkey[a_dev_server_name_here_ed25519]: Invalid value "ed25519". Valid values are ssh-dss, ssh-rsa, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521. 
```

I have no idea why though. Basically i'm assigned this one node to a generic class i have that should setup basics. 

The ssh part that fails (found by commenting out other stuff) is this 
```
class { 'ssh::server':
    storeconfigs_enabled => $storeconfigs_enabled,
    options => merge($options, $ciphers, $macs),
  }
```

It doesn't seem to have anything to do with the actual content of the variables here but could be. Just can't figure it out :( 

Puppet server: 3.8.7
Puppet agent: 3.4.0

Hope somebody can help. Found another thread were the person talked about old module on the node, but cannot replicate the solution for myself.
https://github.com/saz/puppet-ssh/issues/105

**Comment by saz** [comment]
I'm sorry, but except for upgrading the module I don't see another solution for your issue.
