### ISSUE TITLE
Typo in REAMDME.md

### ISSUE THREAD

**Issue by Joachim-42he** [saz/puppet-ssh#271]
Hi saz,

there is a small, but annoying typo in the README.md:

In the very first hiera.example, the setting for the match group is listed as 
`ssh::server_match_block:`
when in fact it should be
`ssh::server::match_block:`

**Comment by patemery67** [comment]
I've submitted pull request #273 to address this issue.
This is my first time contributing to anything. I hope I'm doing this right
