### ISSUE TITLE
provide an option for /etc/sysconfig/sshd

### ISSUE THREAD

**Issue by shibumi** [saz/puppet-ssh#276]
On CentOS and Fedora there is a file called `/etc/sysconfig/sshd`. This file has the following content:
```
# Configuration file for the sshd service.

# The server keys are automatically generated if they are missing.
# To change the automatic creation, adjust sshd.service options for
# example using  systemctl enable sshd-keygen@dsa.service  to allow creation
# of DSA key or  systemctl mask sshd-keygen@rsa.service  to disable RSA key
# creation.

# System-wide crypto policy:
# To opt-out, uncomment the following line
#CRYPTO_POLICY=
```

This file takes care of the crypto policy. For example you can't overwrite ciphers in your `/etc/ssh/sshd_config` if you don't uncomment the `CRYPTO_POLICY=` line. So please provide a way to override the crypto policy.

**Comment by slauger** [comment]
I solved it via file_line in my environment. Maybe not the best but a simple solution. 
```
  if ($facts['os']['family'] == 'RedHat') {
    if ($facts['os']['release']['major'] == '8') {
      file_line { 'disable-system-wide-crypto-policy':
        path    => '/etc/sysconfig/sshd',
        line   => 'CRYPTO_POLICY=',
        match   => '^CRYPTO_POLICY\=',
      }
    }
  }
```
Managing the complete content of `/etc/sysconfig/sshd` (or `/etc/default/sshd` on osfamily Debian) is almost impossible in my eyes. There are way too many differences between all the supported Linux distributions.

**Comment by saz** [comment]
I'm open for any PR with a good solution, but I think it makes more sense to use `file_line` as suggested by @slauger
