### ISSUE TITLE
KexAlgorithm and MACs options appear to be ignored

### ISSUE THREAD

**Issue by vollmerk** [saz/puppet-ssh#278]
``` 
class { '::ssh':
    storeconfigs_enabled  => false,
    server_options  => {
      'HostKey'                         => [' /etc/ssh/ssh_host_rsa_key','/etc/ssh/ssh_host_ecdsa_key'],
      'Ciphers'                         =>'aes256-ctr,aes192-ctr,aes128-ctr',
      'MACs'                            => 'hmac-sha2-512,hmac-sha2-256',
      'KexAlgorithms'                   => 'diffie-hellman-group-exchange-sha256',
    },
  }
```

the Cipher and HostKey get set as expected, however Kex and MAC are never set. `'saz-ssh', '5.0.0'`

**Comment by saz** [comment]
I'm unable to reproduce this issue with release 6.0.0
- Can you give 6.0.0 a try and let me know?
- On which distribution is this happening for you?
- Is this happening for all machines or only on some/one?

**Comment by vollmerk** [comment]
Updated to 6.0.0 and it appears to work perfectly, thanks for the response. Closing.
