### ISSUE TITLE
cannot collect exported resources without storeconfigs being set

### ISSUE THREAD

**Issue by htj** [saz/puppet-ssh#291]
Hi

Thanks for making this module.

For each puppet invocation, we see this output:

Warning: You cannot collect exported resources without storeconfigs being set; the export is ignored (file: /var/cache/cosmos/model/modules/ssh/manifests/hostkeys.pp, line: 32, column: 7)
Warning: You cannot collect exported resources without storeconfigs being set; the export is ignored (file: /var/cache/cosmos/model/modules/ssh/manifests/hostkeys.pp, line: 32, column: 7)
Warning: You cannot collect exported resources without storeconfigs being set; the export is ignored (file: /var/cache/cosmos/model/modules/ssh/manifests/hostkeys.pp, line: 32, column: 7)
Warning: You cannot collect exported resources without storeconfigs being set; the export is ignored (file: /var/cache/cosmos/model/modules/ssh/manifests/hostkeys.pp, line: 32, column: 7)
Warning: You cannot collect exported resources without storeconfigs being set; the collection will be ignored (file: /var/cache/cosmos/model/modules/ssh/manifests/knownhosts.pp, line: 9, column: 7)

I realize it is just a warning, but it is a bit annoying, and would be nice if it wasn't there.

Note that we run puppet in a bit of a weird setup (no master, but have a program on the hosts fetch the manifests and run them perodically). I'm not sure if this is part of the reason, but we don't see anything similar on the 20 or so other modules we use.

EDIT: We are on 6.0.0, but it doesn't look like anything in 6.1.0 fixes this.

**Comment by saz** [comment]
Without a master, it's not possible to use exported resources. Here it's the export of host keys.
Use `storeconfigs_enabled => false`

**Comment by saz** [comment]
@htj any news?

**Comment by htj** [comment]
Sorry, was on easter vacation.

Thanks for the help, this removes the statements. Not sure how I missed it in the first place :-)
