### ISSUE TITLE
Annoying fqdn_keytype name in known_hosts

### ISSUE THREAD

**Issue by pstray** [saz/puppet-ssh#302]
Is there a way to get rid of the fqdn_keytype name that the generate known_hosts file has for each line... I known it really doesn't hurt, but it annoys me that it is there, since it is not a valid alias for the host.

**Comment by saz** [comment]
Can you add an example line, please?

**Comment by pstray** [comment]
Currently my `ssh_known_hosts`-file looks a bit like the following... the first token (HOST1_rsa and such) on the line is the resource-name i think, and not a valid host name, thus I would prefer it not to be there at all.

```
FQDN1_rsa,IP1,HOST1,FQDN1 ssh-rsa AAAA...
FQDN1_ecdsa,IP1,HOST1,FQDN1 ecdsa-sha2-nistp256 AAAA...
FQDN1_ed25519,IP1,HOST1,FQDN1 ssh-ed25519 AAAA...
FQDN2_rsa,IP2,HOST2,FQDN2 ssh-rsa AAAA...
FQDN2_ecdsa,IP2,HOST2,FQDN2 ecdsa-sha2-nistp256 AAAA...
FQDN2_ed25519,IP2,HOST2,FQDN2 ssh-ed25519 AAAA...
```

**Comment by saz** [comment]
Now I get it. That's not possible as this will result in a duplicate resource.

Have a look at https://github.com/saz/puppet-ssh/blob/6e0f430034cf349c8b613d16cf9e3a52f63183e0/manifests/hostkeys.pp#L46

**Comment by pstray** [comment]
So this is more a problem with how the sshkey resource works...

**Comment by saz** [comment]
Maybe it's possible if the title is set to fqdn and the value for name is unique. I'll check that.

**Comment by saz** [comment]
No, sorry. I don't see any way to solve this.
