### ISSUE TITLE
How is ssh_known_hosts managed?

### ISSUE THREAD

**Issue by acullenhms** [saz/puppet-ssh#303]
Hi Saz -

I'm trying to troubleshoot an issue amidst our upgrade to puppet5. We've worked out every bug we've encountered thus far save for one - even though collect_enabled is true, and the rest of our SSH settings and host keys are being propagated correctly, /etc/ssh_known_hosts isn't collecting / populating keys. 

I've been trying to test the cause of this, but I can't seem to find _how_ they are populated in the first place.

Looking at knownhosts.pp in the module manifest, 

```
class ssh::knownhosts(
  $collect_enabled = $ssh::params::collect_enabled,
  $storeconfigs_group = undef,
) inherits ssh::params {
  if ($collect_enabled) {
    resources { 'sshkey':
      purge => true,
    }

    if $storeconfigs_group {
    Sshkey <<| tag == "hostkey_${storeconfigs_group}" |>>
    } else {
      Sshkey <<| |>>
    }
  }
}
~
```

It seems like this bit is the important part, but this is basically magic to me - I'm unfamiliar with this syntax and what this is actually doing:
`Sshkey <<| tag == "hostkey_${storeconfigs_group}" |>>`

What hiera variable are these keys stored in? Or are they not stored in a variable at all, in which case - how are these being collected and distributed? Am I looking in the wrong place?

Thanks!

**Comment by saz** [comment]
hostkeys are collected using exported resources.

If you're not setting `storeconfigs_group` to any value explicitly, it will be undef and the part `Sshkey <<| |>>` is used to realize all exported resources of the `sshkey` type.

Have a look at https://puppet.com/docs/puppet/6.18/lang_exported.html for more details on that.

If there is no error message shown at all, I'd need to see the part of your manifest and any hiera data related to the ssh module to help you a bit better.

**Comment by acullenhms** [comment]
Ah that is a very helpful resource, thank you. 

Here is how we have things defined in our manifests: ($ssh_keys is set to true, verified)

from ::base
```
  if $ssh_keys == true {
    #For all hosts, gather and collect ssh host keys
    include ::ssh::hostkeys
    include ::ssh::knownhosts
  }
```
from ::common
```
if $::profile::base::ssh_keys {
      include ssh::client
      include ssh::server
}
else {
  class { 'ssh':
    storeconfigs_enabled => false,
  }
}

```


As far as Hiera data goes, this is all we have defined - nothing related to knownhosts:
```
ssh::server::options:
  'ClientAliveInterval': '120'
  'ClientAliveCountMax': '720'
  'RhostsRSAAuthentication': 'yes'
  'HostbasedAuthentication': 'yes'
ssh::client::options:
  'EnableSSHKeysign': 'yes'
  'HostbasedAuthentication': 'yes'
  'Host *':
    'ForwardX11Trusted': 'yes'
    'HashKnownHosts': 'yes'
    'GSSAPIAuthentication': 'yes'
    'SendEnv': 'LANG LC_*'
```

**Comment by saz** [comment]
Hmm. I don't get it, why you're doing it like this.

You might also just use
```puppet
class { 'ssh':
  storeconfigs_enabled => $profile::base::ssh_keys,
}
```
This should give you the same result, with less lines :-)

But maybe I'm not understanding, what you're trying to achieve.
The part in `::base` seems redundant to me, as both `ssh::client` and `ssh::server` have a parameter `storeconfigs_enabled` (which is set to `true` by default) and will include both `ssh::hostkeys` and `ssh::knownhosts`.

Even if you said, that you've verified that `$ssh_keys` is set to `true`: are you sure that's the case for `$profile::base::ssh_keys`?
As I'm unable to see if - for example - `common` is inheriting `base`, it's hard to understand that part.

**Comment by acullenhms** [comment]
You are correct, it is redundant as written. I believe it was done that way because base was going to be the absolute baseline configuration - which we wanted to always include hostkeys and knownhosts, and then nodes that get common get additional configuration e.g. sshd. You're right though, we may be due for a bit of refactoring ;)

Common in this instance is inheriting base profile params, yes. I just wanted to illustrate the minimalism of our current config. 

I've also double-checked that $profile::base::ssh_keys is in fact inherited and true

```
    if $::profile::base::ssh_keys {
      file {'/etc/ssh-test':
        ensure  => present,
        content => "Val is: ${::profile::base::ssh_keys}"
      }
      include ssh::client
      include ssh::server
    }
```

```
[root@compute-dev]# cat /etc/ssh-test
Val is: true
```

ssh_known_hosts is created, but empty of keys.
```
[root@compute-dev]# cat /etc/ssh/ssh_known_hosts
# HEADER: This file was autogenerated at 2020-08-27 14:12:59 -0400
# HEADER: by puppet.  While it can still be managed manually, it
# HEADER: is definitely not recommended.

```

**Comment by saz** [comment]
fyi:
```puppet
notify { $profile::base::ssh_keys: }
```
a bit easier to get some more details instead of writing a file ;-)

Can you check if there's anything exported using a puppetdb query?
e.g. `puppet query "resources[title]{ type = 'Sshkey' and exported = true}" --urls http://localhost:8080` run as puppet user on your puppet master.

Please keep in mind, that the title might reveal sensitive details you don't want to post publically

**Comment by acullenhms** [comment]
This is resolved. Thanks for your help, you gave me the push in the direction I needed to solve this:

Our issue boiled down to the new master not using puppetdb as storeconfigs_backend. 

Modifying that setting on the master (and updating our puppetdb-termini package, for good measure) gave us the SSH keys.

Closing now. Thanks again!
