### ISSUE TITLE
defining multiple ssh::client::config::user resources for the same user doesn't work as intended

### ISSUE THREAD

**Issue by rbelnap** [saz/puppet-ssh#304]
Pull request #260 should allow multiple definitions for the same user, however this doesn't work because $name is being used for the concat tag.  Since multiple defines will have different $name the concat_fragment will only add the first one (where concat_file is defined).

The tag should be keyed off of $user, not $name (I'd think `tag    => "${user}_ssh_config",` would be appropriate)

**Comment by saz** [comment]
I don't see a reason for `tag` at all, as `concat_file` will search for `target`, `title` or `tag` matching.
