### ISSUE TITLE
Upgrade on non-enterprise puppet fails with missing pe_license feature

### ISSUE THREAD

**Issue by d33psky** [saz/puppet-ssh#316]
puppet module upgrade saz-ssh --version 8.0.0 --modulepath modules --verbose --debug
...
Error: Could not upgrade module 'saz-ssh' (v2.9.1 -> v8.0.0)
  No version of 'saz-ssh' can satisfy all dependencies
    Use `puppet module upgrade --ignore-dependencies` to upgrade only this module

Using --debug shows that it tries to download pe_license library :
Debug: Failed to load library 'pe_license' for feature 'pe_license': cannot load such file -- pe_license

**Comment by saz** [comment]
There's no version of this module supporting all (versioned) dependencies on your installation.
E.g. stdlib is set to an older version than this module requires in version 8.0.0

Not really much I can do about, as this is something happening as soon as you're using a few modules.
