### ISSUE TITLE
Use regular hiera parameter lookup instead of manual calling lookup or add flag

### ISSUE THREAD

**Issue by c33s** [saz/puppet-ssh#327]
currently this module uses a mix out of automatic hiera class parameter lookup and a manual call to `lookup`
```puppet
class ssh::server (
...
  Hash    $options              = {},
...
) inherits ssh::params {
  $hiera_options = lookup("${module_name}::server::options", Optional[Hash], 'deep', {})
...
  $fin_options = deep_merge($hiera_options, $options)
```

this can lead to an unexpected behavior if you define `ssh::server_options` and expect it to obey the defined `lookup_options`

if i define the following in `common.yaml`:
```yaml
ssh::server_options:
  Include: '/etc/ssh/sshd_config.d/*.conf'
  LogLevel: VERBOSE
```
i cannot simple define the same without `Include` for a specific host which does not support the include funciton. why not only lookup the options via hiera? with hiera i can define the merge behavior myself and are not stuck with an enforced deep merge.
```yaml
ssh::server_options: {merge: {strategy: deep, merge_hash_arrays: true, knockout_prefix: "--", sort_merged_arrays: false}}
```

or what about adding a flag for this?
```puppet
  Boolean $do_extra_hiera_lookup        = true
  String $extra_hiera_lookup_merge_behavior = 'deep'
  
) inherits ssh::params {
  # Merge hashes from multiple layer of hierarchy in hiera
  if ($do_extra_hiera_lookup) {
    $hiera_options = lookup("${module_name}::server::options", Optional[Hash], $extra_hiera_lookup_merge_behavior, {})
    $hiera_match_block = lookup("${module_name}::server::match_block", Optional[Hash], $extra_hiera_lookup_merge_behavior, {})
  } else {
    $hiera_options = {}
    $hiera_match_block = {}
  }
...
```

this would really help

**Comment by SimonHoenscheid** [comment]
@c33s that would be a good addition to PR #325 . I thought about this as well.

**Comment by c33s** [comment]
@SimonHoenscheid that would be nice :)

**Comment by saz** [comment]
This is some old behavior from an earlier hiera time :-) 
I don't see a reason to keep it like that.

@SimonHoenscheid maybe you can add it to your PR #325?

**Comment by SimonHoenscheid** [comment]
@saz I can add an other PR that can be merged directly afterwards
