### ISSUE TITLE
Duplicate declaration when using class ssh::server directly

### ISSUE THREAD

**Issue by algolsigfrid** [saz/puppet-ssh#335]
Apologies because this might be more an user error than a bug.

I am trying to use the class _ssh::server_ directly from within a profile class and I am getting a _duplicate declaration_ error. The documentation for the module suggests that I should be able to use the _ssh::server_ class directly and I do not understand what I am doing wrong. 

```
class profile::ssh::server {
  
  class { 'ssh::server':
    storeconfigs_enabled => true,
    validate_sshd_file   => true,
    options              => {
      'AddressFamily'                   => 'inet',
       ... ... ... more options here ....
     },
  }
}
```
And the error message indicates a duplicate declaration at _/site/profile/manifests/ssh/server.pp_ (my profile class) and _/modules/ssh/manifests/init.pp_ (this module managed by r10k)

I am following the example documentation here
https://github.com/saz/puppet-ssh/tree/v9.0.0#server-only

I have searched all over my control repository and I do not see any other references to either _class ssh_ or _class ssh::server_

Any pointers are appreciated. 

Thank you in advance for your help.

**Comment by alexskr** [comment]
This functionality broke in v9.0.0 release.  The fix is in place but has not been released yet.

**Comment by saz** [comment]
I've just release v10.0.0 which should resolve this issue
