### ISSUE TITLE
Feature Request: Hashed hostnames in ssh_known_hosts

### ISSUE THREAD

**Issue by JRDavisUF** [saz/puppet-ssh#337]
It would be nice if hashed hostnames could/would be used in /etc/ssh/ssh_known_hosts

Maybe something like: ssh-keygen -H -f /etc/ssh/ssh_known_hosts
as an Exec executed after a change to the file /etc/ssh/ssh_known_hosts 
followed by a purge of /etc/ssh/ssh_known_host.old

**Comment by saz** [comment]
This is something, which might be added with a parameter.

I'm open for any PRs, but just executing a command won't be enough, I think, as we need to somehow validate, if all keys are in there.

**Comment by saz** [comment]
As there's no update and this is quite complicated, I'll close this issue. Feel free to (re-)open it.
