### ISSUE TITLE
class containment

### ISSUE THREAD

**Issue by jhoblitt** [saz/puppet-ssh#367]
I would like to be able to order my catalog such that some resources are applied only after the ssh/sshd config is converged. However, `Class[ssh] -> Class[foo]` doesn't work as expected as there is no containment for the various sub-classes in the module.

```puppet
Class[ssh::client::config] -> Class[foo]
Class[ssh::server::config] -> Class[foo]
```

Would probably work but both of the `::config` classes are labeled as api private.  There should be public class(es) in the module that can be used for ordering.

**Comment by saz** [comment]
I guess, replacing some `include ssh::some_class` by `contain ssh::some_class` should resolve this. :thinking: 

I'll create a PR asap.
