### ISSUE TITLE
Removal of a node does not result in removal of ssh_known_hosts entry

### ISSUE THREAD

**Issue by mcallaway** [saz/puppet-ssh#64]
With storeconfigs enabled and keys in puppetdb, ssh::knownhosts collects them and writes to /etc/ssh/ssh_known_hosts. But if a node is then deactivated, its entry is not removed from ssh_known_hosts. If that file is truncated, it can be remade without the removed node, but it seems like it should be possible to have node deactivation result in the removal of the key from ssh_known_hosts.

**Comment by claflico** [comment]
Not hijacking but this is the 3rd reference I've seen to known_hosts & puppetdb when searching how to use this module better. Is puppetdb required in order for the agent's known_host file to get populated? If so, I don't see puppetdb listed in the module dependencies or on the README.

**Comment by saz** [comment]
@mcallaway This issue is resolved in the current master.

@claflico storeconfigs is required for known_hosts to work. If you see a problem, please feel free to open a new issue
