### ISSUE TITLE
Allow host keys to be configured in hiera

### ISSUE THREAD

**Issue by voidus** [saz/puppet-ssh#73]
Not sure this is the best of all possible ways. It would keep the data out of the manifest, though.

**Comment by Oyabi** [comment]
I agree.

**Comment by saz** [comment]
I'm happy to see a pull request for this.

**Comment by saz** [comment]
Any news on this?

**Comment by saz** [comment]
I'll close this issue for now. If you're willing to send in a pull request, I'll be happy to merge it.

**Comment by voidus** [comment]
I don't think I'll find time to do this. Sorry.

 If I were you, I'd keep the ticket open for documentation and in hope that someone will implement this. Just my 2 cents.
