### ISSUE TITLE
Using match_block causes Error 400 on SERVER: Invalid tag

### ISSUE THREAD

**Issue by nbeernink** [saz/puppet-ssh#74]
I'm trying to use match_block as shown in the example. But get an internal server error:
Error 400 on SERVER: Invalid tag '::ssh::server::match_block'

```
  ::ssh::server::match_block { 'sftpusers':
    type                       => 'Group',
    options                    => {
      'ChrootDirectory'        => "/var/sftp/",
      'ForceCommand'           => 'internal-sftp',
      'AllowTcpForwarding'     => 'no',
      'X11Forwarding'          => 'no',
    }
  }
```

Am I using it incorrectly? The debug output for puppet agent -t --debug doesn't show any additional info.

**Comment by wouteroostervld** [comment]
Hi Niek,

You need to "include ssh" in your custom class definition.

The README could use an complete example.

**Comment by nbeernink** [comment]
Thanks, the "fix" wasn't to include the ssh class, that was already done via foreman, however it was to checkout the master branch. I thought I could use custom match blocks with the 2.4.0 release, but apparently the feature was added later. So I should have read the README from the 2.4.0 release instead of the one from master. It's fixed indeed by checking out master instead of 2.4.0. Thanks!
