### ISSUE TITLE
Allow Options like HostKey to be specified multiple times

### ISSUE THREAD

**Issue by voidus** [saz/puppet-ssh#81]
The HostKey option for sshd_config can be specified multiple times. Currently, it is not possible to add multiple HostKey statements to the config, because additional Options are stored in a Hash.

One possible Solution would be to allow HostKey to be an array which expands to multiple HostKey-Statements. How do you feel about this approach?

**Comment by Seegras** [comment]
I second that. This is needed.

**Comment by voidus** [comment]
I'll see if I find time to implement this in the next days.

**Comment by gertvdijk** [comment]
As far as I know, this is perfectly possible using a Array as a value to the Hash key.

For me

    server_options => ["/etc/ssh/ssh_host_ed25519_key", "/etc/ssh/ssh_host_rsa_key",]

Results in

    HostKey /etc/ssh/ssh_host_ed25519_key
    HostKey /etc/ssh/ssh_host_rsa_key

Nice!

This is [magic in the templates](https://github.com/saz/puppet-ssh/blob/4a3c417e08c4d66ed658850ded467ae04d5b30c3/templates/sshd_config.erb#L31).

**Comment by Seegras** [comment]
Ah nice, in hiera this looks like this:
 ```
ssh::server_options:
  HostKey:
    - '/etc/ssh/ssh_host_ed25519_key'
    - '/etc/ssh/ssh_host_rsa_key'
```
works. So at least regarding HostKey the issue can be closed.

**Comment by voidus** [comment]
Oh, yeah sure. I didn't get that.
