### ISSUE TITLE
Map boolean config values to the real pairs

### ISSUE THREAD

**Issue by hron84** [saz/puppet-ssh#88]
The module does not map booleans from YAML/JSON to the value what the ssh/sshd accepts. For example, PrintMotd is a boolean config option, can be true or false, however, if you provide true (e.g. foreman converts all unquoted yes / no to boolean values true / false), the module generates wrong config code (true instead of yes) what sshd does not understand and fails to start. 

The workaround is easy: in foreman you should always quote 'yes' / 'no' values to ensure it will be written correctly, however the module should know this mapping, especially because the OpenSSH currently not uses any config option where true or false makes sense.

**Comment by saz** [comment]
Please feel free to send a pull request resolving this issue. I'm not using foreman and I'm therefore unable to verify if it's working or not.

**Comment by halfninja** [comment]
Trivially reproduced by passing a boolean value with an option, tested and fixed by #100.

**Comment by hron84** [comment]
@halfninja cool, thanks for your help.
